# Generated by Django 5.2.8 on 2025-12-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_bathrooms_property_kitchen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
    ]
