# Generated by Django 5.2.8 on 2025-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='preferred_move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
